---
title: "<i class='bi bi-shield-lock'></i> Syllabus"
---

::: {.callout-important}
This information applies to the second half of Term 2. For first half content, see Canvas
:::

## Course info

**Co-Instructors**:\
Lang Wu (Jan 9 – Feb 28), Daniel McDonald (Mar 2 – Apr 13)\
Office: Earth Sciences Building 3106\
Website: <https://dajmcdon.github.io/>\
Email: [daniel\@stat.ubc.ca](mailto:daniel@stat.ubc.ca){.email}

**Office hours**:\
I'm happy to arrange time as needed. Just message me on Slack.

**Course webpage**:\
WWW: <https://stat550-2021.github.io/>\
Github Org: <https://github.com/stat550-2021/>

**Lectures**:\
Tue/Thu 14:30 - 16:00, ESB 4192

## Course content

This graduate-level course is designed to serve two overlapping purposes: (1) help students prepare for the Consulting Practicum Course (STAT 551) and/or work with [ASDa](https://asda.stat.ubc.ca) and (2) give students appropriate professional skills for research, thesis writing, other projects. The major goals are to

1.  Read, understand, explain academic statistical concepts to non-statisticians
2.  Give high-quality presentations
3.  Learn how to convert subject-matter questions into statistical ones.
4.  Communicate statistical conclusions carefully and rigorously, in writing and presentations
5.  Use reasonable statistical workflows
6.  Conduct quality computer experiments
7.  Use version control effectively
8.  Write verifiable, reproducible code

## Assessment opportunities

-   1 individual project, per half-term (30%)
-   1 individual presentation, delivered in either half (20%)
-   Homework in groups, per half-term (30%)
-   Class participation and discussion (20%)

### Presentation

Each student will give a 20-minute presentation on a consulting topic with slides. This will only happen once during the term. Some did it during the first half.


### Participation and discussion (professionalism)

Excellent professionalism means going above and beyond in terms of in-class participation and contributions on the discussion board. Regularly responding to fellow students is a step toward the excellence. Failing to participate in class, regularly skipping class, leaving your homework team out to dry, will result in reduced scores. This should also be rare.

This is a required graduate course and a prerequisite for your degree. Failing to support your classmates or take this course seriously will be dealt with harshly. A rubric for this component is linked below.

-   [Professionalism rubric]()

## Important considerations

### University policies

UBC provides resources to support student learning and to maintain healthy lifestyles but recognizes that sometimes crises arise and so there are additional resources to access including those for survivors of sexual violence. UBC values respect for the person and ideas of all members of the academic community. Harassment and discrimination are not tolerated nor is suppression of academic freedom. UBC provides appropriate accommodation for students with disabilities and for religious, spiritual and cultural observances. UBC values academic honesty and students are expected to acknowledge the ideas generated by others and to uphold the highest academic standards in all of their actions. Details of the policies and how to access support are available [here](http://senate.ubc.ca/policies-resources-support-student-success).

### Academic honesty and standards

**UBC Vancouver Statement**

Academic honesty is essential to the continued functioning of the University of British Columbia as an institution of higher learning and research. All UBC students are expected to behave as honest and responsible members of an academic community. Breach of those expectations or failure to follow the appropriate policies, principles, rules, and guidelines of the University with respect to academic honesty may result in disciplinary action.

For the full statement, please see the [2020/21 Vancouver Academic Calendar](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,286,0,0#15620)

### Academic Concessions

These are handled according to UBC policy. Please see

* [UBC student services](https://students.ubc.ca/enrolment/academic-learning-resources/academic-concessions) 
* [UBC Vancouver Academic Calendar](http://www.calendar.ubc.ca/vancouver/index.cfm?tree=3,0,0,0) 
* [Faculty of Science Concessions](https://science.ubc.ca/students/advising/concession)

### Take care of yourself

Course work at this level can be intense, and I encourage you to take care of yourself. Do your best to maintain a healthy lifestyle this semester by eating well, exercising, avoiding drugs and alcohol, getting enough sleep and taking some time to relax. This will help you achieve your goals and cope with stress. I struggle with these issues too, and I try hard to set aside time for things that make me happy (cooking, playing/listening to music, exercise, going for walks).

All of us benefit from support during times of struggle. If you are having any problems or concerns, do not hesitate to speak with me. There are also many resources available on campus that can provide help and support. Asking for support sooner rather than later is almost always a good idea.

If you or anyone you know experiences any academic stress, difficult life events, or feelings like anxiety or depression, I strongly encourage you to seek support. UBC Counseling Services is here to help: call 604 822 3811 or visit their [website](https://students.ubc.ca/health/counselling-services). Consider also reaching out to a friend, faculty member, or family member you trust to help get you the support you need.
